# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Danger

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bbbb23ac61324d92b4ba8409a7b22301 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1652489154314511a0ce868d55096d4f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bbbb23ac61324d92b4ba8409a7b22301 }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Danger'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bff05cc316aa4d64a7de08c63fe5152b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bbbb23ac61324d92b4ba8409a7b22301 }}/nginx:${{ github.sha }}'